name: Build

on:
  - push

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'app.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'EsoAddOnsUpdater'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            EsoAddOnsUpdater.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
